export const GET_LIST_DEPOSIT_SATOSHI_REQUESTED = 'GET_LIST_DEPOSIT_SATOSHI_REQUESTED';
export const GET_LIST_DEPOSIT_SATOSHI_SUCCESS = 'GET_LIST_DEPOSIT_SATOSHI_SUCCESS';
export const GET_LIST_DEPOSIT_SATOSHI_FAILED = 'GET_LIST_DEPOSIT_SATOSHI_FAILED';

export const GET_STAT_DEPOSIT_SATOSHI_REQUESTED = 'GET_STAT_DEPOSIT_SATOSHI_REQUESTED';
export const GET_STAT_DEPOSIT_SATOSHI_SUCCESS = 'GET_STAT_DEPOSIT_SATOSHI_SUCCESS';
export const GET_STAT_DEPOSIT_SATOSHI_FAILED = 'GET_STAT_DEPOSIT_SATOSHI_FAILED';
