export const GET_HOMEPAGE_BANNER_CONFIG_REQUESTED = 'GET_HOMEPAGE_BANNER_CONFIG_REQUESTED';
export const GET_HOMEPAGE_BANNER_CONFIG_SUCCESS = 'GET_HOMEPAGE_BANNER_CONFIG_SUCCESS';
export const GET_HOMEPAGE_BANNER_CONFIG_FAILED = 'GET_HOMEPAGE_BANNER_CONFIG_FAILED';
