export const GET_EVENT_REQUESTED = 'GET_EVENT_REQUESTED';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILED = 'GET_EVENT_FAILED';

export const GET_LIST_STATISTIC_GAME_REQUESTED = 'GET_LIST_STATISTIC_GAME_REQUESTED';
export const GET_LIST_STATISTIC_GAME_SUCCESS = 'GET_LIST_STATISTIC_GAME_SUCCESS';
export const GET_LIST_STATISTIC_GAME_FAILED = 'GET_LIST_STATISTIC_GAME_FAILED';
