export const GET_CHICKEN_FARM_STATS_REQUESTED = 'GET_CHICKEN_FARM_STATS_REQUESTED';
export const GET_CHICKEN_FARM_STATS_SUCCESS = 'GET_CHICKEN_FARM_STATS_SUCCESS';
export const GET_CHICKEN_FARM_STATS_FAILED = 'GET_CHICKEN_FARM_STATS_FAILED';

export const GET_ADULT_STATS_REQUESTED = 'GET_ADULT_STATS_REQUESTED';
export const GET_ADULT_STATS_SUCCESS = 'GET_ADULT_STATS_SUCCESS';
export const GET_ADULT_STATS_FAILED = 'GET_ADULT_STATS_FAILED';
