export const GET_PARTNER_DETAIL_REQUESTED = 'GET_PARTNER_DETAIL_REQUESTED';
export const GET_PARTNER_DETAIL_SUCCESS = 'GET_PARTNER_DETAIL_SUCCESS';
export const GET_PARTNER_DETAIL_FAILED = 'GET_PARTNER_DETAIL_FAILED';

export const GET_COMMISSION_REQUESTED = 'GET_COMMISSION_REQUESTED';
export const GET_COMMISSION_SUCCESS = 'GET_COMMISSION_SUCCESS';
export const GET_COMMISSION_FAILED = 'GET_COMMISSION_FAILED';

export const GET_CASHBACK_WALLET_REQUESTED = 'GET_CASHBACK_WALLET_REQUESTED';
export const GET_CASHBACK_WALLET_SUCCESS = 'GET_CASHBACK_WALLET_SUCCESS';
export const GET_CASHBACK_WALLET_FAILED = 'GET_CASHBACK_WALLET_FAILED';

export const GET_CASHBACK_TRANSACTION_REQUESTED = 'GET_CASHBACK_TRANSACTION_REQUESTED';
export const GET_CASHBACK_TRANSACTION_SUCCESS = 'GET_CASHBACK_TRANSACTION_SUCCESS';
export const GET_CASHBACK_TRANSACTION_FAILED = 'GET_CASHBACK_TRANSACTION_FAILED';

export const GET_NOTIFICATIONS_REQUESTED = 'GET_NOTIFICATIONS_REQUESTED';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';

export const GET_ACCOUNT_REFERRED_REQUESTED = 'GET_ACCOUNT_REFERRED_REQUESTED';
export const GET_ACCOUNT_REFERRED_SUCCESS = 'GET_ACCOUNT_REFERRED_SUCCESS';
export const GET_ACCOUNT_REFERRED_FAILED = 'GET_ACCOUNT_REFERRED_FAILED';

export const GET_DAILY_SPIN_REQUESTED = 'GET_DAILY_SPIN_REQUESTED';
export const GET_DAILY_SPIN_SUCCESS = 'GET_DAILY_SPIN_SUCCESS';
export const GET_DAILY_SPIN_FAILED = 'GET_DAILY_SPIN_FAILED';

export const GET_WALLET_INFO_REQUESTED = 'GET_WALLET_INFO_REQUESTED';
export const GET_WALLET_INFO_SUCCESS = 'GET_WALLET_INFO_SUCCESS';
export const GET_WALLET_INFO_FAILED = 'GET_WALLET_INFO_FAILED';
