export const GET_LIST_FRIEND_INVITATION_REQUESTED = 'GET_LIST_FRIEND_INVITATION_REQUESTED';
export const GET_LIST_FRIEND_INVITATION_SUCCESS = 'GET_LIST_FRIEND_INVITATION_SUCCESS';
export const GET_LIST_FRIEND_INVITATION_FAILED = 'GET_LIST_FRIEND_INVITATION_FAILED';
