export const GET_LUCKY_SPIN_DETAIL_REQUESTED = 'GET_LUCKY_SPIN_DETAIL_REQUESTED';
export const GET_LUCKY_SPIN_DETAIL_SUCCESS = 'GET_LUCKY_SPIN_DETAIL_SUCCESS';
export const GET_LUCKY_SPIN_DETAIL_FAILED = 'GET_LUCKY_SPIN_DETAIL_FAILED';

export const GET_LIST_USER_REQUESTED = 'GET_LIST_USER_REQUESTED';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAILED = 'GET_LIST_USER_FAILED';
