export const GET_ANNOUNCEMENT_BITFARM_REQUESTED = 'GET_ANNOUNCEMENT_BITFARM_REQUESTED';
export const GET_ANNOUNCEMENT_BITFARM_SUCCESS = 'GET_ANNOUNCEMENT_BITFARM_SUCCESS';
export const GET_ANNOUNCEMENT_BITFARM_FAILED = 'GET_ANNOUNCEMENT_BITFARM_FAILED';
