export const GET_DASHBOARD_ACCOUNT_TOTAL_REQUESTED = 'GET_DASHBOARD_ACCOUNT_TOTAL_REQUESTED';
export const GET_DASHBOARD_ACCOUNT_TOTAL_SUCCESS = 'GET_DASHBOARD_ACCOUNT_TOTAL_SUCCESS';
export const GET_DASHBOARD_ACCOUNT_TOTAL_FAILED = 'GET_DASHBOARD_ACCOUNT_TOTAL_FAILED';

export const GET_DASHBOARD_ACCOUNT_REQUESTED = 'GET_DASHBOARD_ACCOUNT_REQUESTED';
export const GET_DASHBOARD_ACCOUNT_SUCCESS = 'GET_DASHBOARD_ACCOUNT_SUCCESS';
export const GET_DASHBOARD_ACCOUNT_FAILED = 'GET_DASHBOARD_ACCOUNT_FAILED';

export const GET_CASHBACK_TOTAL_REQUESTED = 'GET_CASHBACK_TOTAL_REQUESTED';
export const GET_CASHBACK_TOTAL_SUCCESS = 'GET_CASHBACK_TOTAL_SUCCESS';
export const GET_CASHBACK_TOTAL_FAILED = 'GET_CASHBACK_TOTAL_FAILED';

export const GET_CASHBACK_REQUESTED = 'GET_CASHBACK_REQUESTED';
export const GET_CASHBACK_SUCCESS = 'GET_CASHBACK_SUCCESS';
export const GET_CASHBACK_FAILED = 'GET_CASHBACK_FAILED';

export const GET_ACCOUNT_KYC_REQUESTED = 'GET_ACCOUNT_KYC_REQUESTED';
export const GET_ACCOUNT_KYC_SUCCESS = 'GET_ACCOUNT_KYC_SUCCESS';
export const GET_ACCOUNT_KYC_FAILED = 'GET_ACCOUNT_KYC_FAILED';

export const GET_ACCOUNT_NON_KYC_REQUESTED = 'GET_ACCOUNT_NON_KYC_REQUESTED';
export const GET_ACCOUNT_NON_KYC_SUCCESS = 'GET_ACCOUNT_NON_KYC_SUCCESS';
export const GET_ACCOUNT_NON_KYC_FAILED = 'GET_ACCOUNT_NON_KYC_FAILED';

export const GET_TOTAL_REFERRAL_AMOUNT_KYC_REQUESTED = 'GET_TOTAL_REFERRAL_AMOUNT_KYC_REQUESTED';
export const GET_TOTAL_REFERRAL_AMOUNT_KYC_SUCCESS = 'GET_TOTAL_REFERRAL_AMOUNT_KYC_SUCCESS';
export const GET_TOTAL_REFERRAL_AMOUNT_KYC_FAILED = 'GET_TOTAL_REFERRAL_AMOUNT_KYC_FAILED';

export const GET_TOTAL_REFERRAL_AMOUNT_NON_KYC_REQUESTED = 'GET_TOTAL_REFERRAL_AMOUNT_NON_KYC_REQUESTED';
export const GET_TOTAL_REFERRAL_AMOUNT_NON_KYC_SUCCESS = 'GET_TOTAL_REFERRAL_AMOUNT_NON_KYC_SUCCESS';
export const GET_TOTAL_REFERRAL_AMOUNT_NON_KYC_FAILED = 'GET_TOTAL_REFERRAL_AMOUNT_NON_KYC_FAILED';

export const GET_TOTAL_ACCOUNT_VNDC_REQUESTED = 'GET_TOTAL_ACCOUNT_VNDC_REQUESTED';
export const GET_TOTAL_ACCOUNT_VNDC_SUCCESS = 'GET_TOTAL_ACCOUNT_VNDC_SUCCESS';
export const GET_TOTAL_ACCOUNT_VNDC_FAILED = 'GET_TOTAL_ACCOUNT_VNDC_FAILED';

export const GET_ACCOUNT_HAVE_PHONE_REQUESTED = 'GET_ACCOUNT_HAVE_PHONE_REQUESTED';
export const GET_ACCOUNT_HAVE_PHONE_SUCCESS = 'GET_ACCOUNT_HAVE_PHONE_SUCCESS';
export const GET_ACCOUNT_HAVE_PHONE_FAILED = 'GET_ACCOUNT_HAVE_PHONE_FAILED';

export const GET_CASHBACK_SUMMARY_REQUESTED = 'GET_CASHBACK_SUMMARY_REQUESTED';
export const GET_CASHBACK_SUMMARY_SUCCESS = 'GET_CASHBACK_SUMMARY_SUCCESS';
export const GET_CASHBACK_SUMMARY_FAILED = 'GET_CASHBACK_SUMMARY_FAILED';

export const GET_BUY_SATOSHI_TOTAL_REQUESTED = 'GET_BUY_SATOSHI_TOTAL_REQUESTED';
export const GET_BUY_SATOSHI_TOTAL_SUCCESS = 'GET_BUY_SATOSHI_TOTAL_SUCCESS';
export const GET_BUY_SATOSHI_TOTAL_FAILED = 'GET_BUY_SATOSHI_TOTAL_FAILED';

export const GET_BUY_SATOSHI_REQUESTED = 'GET_BUY_SATOSHI_REQUESTED';
export const GET_BUY_SATOSHI_SUCCESS = 'GET_BUY_SATOSHI_SUCCESS';
export const GET_BUY_SATOSHI_FAILED = 'GET_BUY_SATOSHI_FAILED';

export const GET_WITHDRAW_SATOSHI_REQUESTED = 'GET_WITHDRAW_SATOSHI_REQUESTED';
export const GET_WITHDRAW_SATOSHI_SUCCESS = 'GET_WITHDRAW_SATOSHI_SUCCESS';
export const GET_WITHDRAW_SATOSHI_FAILED = 'GET_WITHDRAW_SATOSHI_FAILED';

export const GET_CASHBACK_AVAILABLE_PERIOD_REQUESTED = 'GET_CASHBACK_AVAILABLE_PERIOD_REQUESTED';
export const GET_CASHBACK_AVAILABLE_PERIOD_SUCCESS = 'GET_CASHBACK_AVAILABLE_PERIOD_SUCCESS';
export const GET_CASHBACK_AVAILABLE_PERIOD_FAILED = 'GET_CASHBACK_AVAILABLE_PERIOD_FAILED';
