export const GET_INTEREST_RATE_REQUESTED = 'GET_INTEREST_RATE_REQUESTED';
export const GET_INTEREST_RATE_SUCCESS = 'GET_INTEREST_RATE_SUCCESS';
export const GET_INTEREST_RATE_FAILED = 'GET_INTEREST_RATE_FAILED';
