export const GET_RANK_DETAIL_REQUESTED = 'GET_RANK_DETAIL_REQUESTED';
export const GET_RANK_DETAIL_SUCCESS = 'GET_RANK_DETAIL_SUCCESS';
export const GET_RANK_DETAIL_FAILED = 'GET_RANK_DETAIL_FAILED';

export const GET_RANK_TABLE_REQUESTED = 'GET_RANK_TABLE_REQUESTED';
export const GET_RANK_TABLE_SUCCESS = 'GET_RANK_TABLE_SUCCESS';
export const GET_RANK_TABLE_FAILED = 'GET_RANK_TABLE_FAILED';
