export const GET_LIST_BROKER_REQUESTED = 'GET_LIST_BROKER_REQUESTED';
export const GET_LIST_BROKER_SUCCESS = 'GET_LIST_BROKER_SUCCESS';
export const GET_LIST_BROKER_FAILED = 'GET_LIST_BROKER_FAILED';

export const GET_LIST_CURRENCY_REQUESTED = 'GET_LIST_CURRENCY_REQUESTED';
export const GET_LIST_CURRENCY_SUCCESS = 'GET_LIST_CURRENCY_SUCCESS';
export const GET_LIST_CURRENCY_FAILED = 'GET_LIST_CURRENCY_FAILED';
