export const GET_LIST_WITHDRAWAL_VNDC_REQUESTED = 'GET_LIST_WITHDRAWAL_VNDC_REQUESTED';
export const GET_LIST_WITHDRAWAL_VNDC_SUCCESS = 'GET_LIST_WITHDRAWAL_VNDC_SUCCESS';
export const GET_LIST_WITHDRAWAL_VNDC_FAILED = 'GET_LIST_WITHDRAWAL_VNDC_FAILED';

export const GET_STAT_WITHDRAWAL_VNDC_REQUESTED = 'GET_STAT_WITHDRAWAL_VNDC_REQUESTED';
export const GET_STAT_WITHDRAWAL_VNDC_SUCCESS = 'GET_STAT_WITHDRAWAL_VNDC_SUCCESS';
export const GET_STAT_WITHDRAWAL_VNDC_FAILED = 'GET_STAT_WITHDRAWAL_VNDC_FAILED';
