export const GET_LIST_STATISTIC_REQUESTED = 'GET_LIST_STATISTIC_REQUESTED';
export const GET_LIST_STATISTIC_SUCCESS = 'GET_LIST_STATISTIC_SUCCESS';
export const GET_LIST_STATISTIC_FAILED = 'GET_LIST_STATISTIC_FAILED';

export const ADD_TO_REWARD = 'ADD_TO_REWARD';
export const DELETE_TO_REWARD = 'DELETE_TO_REWARD';
export const RESET_REWARD = 'RESET_REWARD';

export const GET_LIST_STATISTIC_WITH_AMOUNT_REQUESTED = 'GET_LIST_STATISTIC_WITH_AMOUNT_REQUESTED';
export const GET_LIST_STATISTIC_WITH_AMOUNT_SUCCESS = 'GET_LIST_STATISTIC_WITH_AMOUNT_SUCCESS';
export const GET_LIST_STATISTIC_WITH_AMOUNT_FAILED = 'GET_LIST_STATISTIC_WITH_AMOUNT_FAILED';
