export const GET_LIST_CHALLENGE_REQUESTED = 'GET_LIST_CHALLENGE_REQUESTED';
export const GET_LIST_CHALLENGE_SUCCESS = 'GET_LIST_CHALLENGE_SUCCESS';
export const GET_LIST_CHALLENGE_FAILED = 'GET_LIST_CHALLENGE_FAILED';
