export const GET_LIST_REQUESTED = 'GET_LIST_REQUESTED';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILED = 'GET_LIST_FAILED';

export const ADD_TO_GOLDEN_EGG = 'ADD_TO_GOLDEN_EGG';
export const DELETE_TO_GOLDEN_EGG = 'DELETE_TO_GOLDEN_EGG';
export const RESET_TO_GOLDEN_EGG = 'RESET_TO_GOLDEN_EGG';
export const UPDATE_TO_GOLDEN_EGG = 'UPDATE_TO_GOLDEN_EGG';
