export const GET_BROKER_TRANSACTION_REQUESTED = 'GET_BROKER_TRANSACTION_REQUESTED';
export const GET_BROKER_TRANSACTION_SUCCESS = 'GET_BROKER_TRANSACTION_SUCCESS';
export const GET_BROKER_TRANSACTION_FAILED = 'GET_BROKER_TRANSACTION_FAILED';

export const GET_LIST_EGG_REQUESTED = 'GET_LIST_EGG_REQUESTED';
export const GET_LIST_EGG_SUCCESS = 'GET_LIST_EGG_SUCCESS';
export const GET_LIST_EGG_FAILED = 'GET_LIST_EGG_FAILED';

export const GET_LIST_CHICKEN_REQUESTED = 'GET_LIST_CHICKEN_REQUESTED';
export const GET_LIST_CHICKEN_SUCCESS = 'GET_LIST_CHICKEN_SUCCESS';
export const GET_LIST_CHICKEN_FAILED = 'GET_LIST_CHICKEN_FAILED';

export const GET_ACCOUNT_TRANSACTION_REQUESTED = 'GET_ACCOUNT_TRANSACTION_REQUESTED';
export const GET_ACCOUNT_TRANSACTION_SUCCESS = 'GET_ACCOUNT_TRANSACTION_SUCCESS';
export const GET_ACCOUNT_TRANSACTION_FAILED = 'GET_ACCOUNT_TRANSACTION_FAILED';
