export const GET_LIST_STATISTIC_REQUESTED = 'GET_LIST_STATISTIC_REQUESTED';
export const GET_LIST_STATISTIC_SUCCESS = 'GET_LIST_STATISTIC_SUCCESS';
export const GET_LIST_STATISTIC_FAILED = 'GET_LIST_STATISTIC_FAILED';
