export const GET_STACKING_DETAIL_REQUESTED = 'GET_STACKING_DETAIL_REQUESTED';
export const GET_STACKING_DETAIL_SUCCESS = 'GET_STACKING_DETAIL_SUCCESS';
export const GET_STACKING_DETAIL_FAILED = 'GET_STACKING_DETAIL_FAILED';

export const GET_STACKING_TABLE_REQUESTED = 'GET_STACKING_TABLE_REQUESTED';
export const GET_STACKING_TABLE_SUCCESS = 'GET_STACKING_TABLE_SUCCESS';
export const GET_STACKING_TABLE_FAILED = 'GET_STACKING_TABLE_FAILED';
