export const GET_LIST_PLAYER_REQUESTED = 'GET_LIST_PLAYER_REQUESTED';
export const GET_LIST_PLAYER_SUCCESS = 'GET_LIST_PLAYER_SUCCESS';
export const GET_LIST_PLAYER_FAILED = 'GET_LIST_PLAYER_FAILED';

export const GET_LIST_PLAYER_STAT_REQUESTED = 'GET_LIST_PLAYER_STAT_REQUESTED';
export const GET_LIST_PLAYER_STAT_SUCCESS = 'GET_LIST_PLAYER_STAT_SUCCESS';
export const GET_LIST_PLAYER_STAT_FAILED = 'GET_LIST_PLAYER_STAT_FAILED';
