export const GET_BROKER_DETAIL_REQUESTED = 'GET_BROKER_DETAIL_REQUESTED';
export const GET_BROKER_DETAIL_SUCCESS = 'GET_BROKER_DETAIL_SUCCESS';
export const GET_BROKER_DETAIL_FAILED = 'GET_BROKER_DETAIL_FAILED';

export const GET_BROKER_TRANSACTION_REQUESTED = 'GET_BROKER_TRANSACTION_REQUESTED';
export const GET_BROKER_TRANSACTION_SUCCESS = 'GET_BROKER_TRANSACTION_SUCCESS';
export const GET_BROKER_TRANSACTION_FAILED = 'GET_BROKER_TRANSACTION_FAILED';

export const GET_BROKER_TRANSACTION_STAT_REQUESTED = 'GET_BROKER_TRANSACTION_STAT_REQUESTED';
export const GET_BROKER_TRANSACTION_STAT_SUCCESS = 'GET_BROKER_TRANSACTION_STAT_SUCCESS';
export const GET_BROKER_TRANSACTION_STAT_FAILED = 'GET_BROKER_TRANSACTION_STAT_FAILED';
