export const GET_LIST_PARTNER_REQUESTED = 'GET_LIST_PARTNER_REQUESTED';
export const GET_LIST_PARTNER_SUCCESS = 'GET_LIST_PARTNER_SUCCESS';
export const GET_LIST_PARTNER_FAILED = 'GET_LIST_PARTNER_FAILED';
