export const GET_LIST_STATISTIC_STACKING_REQUESTED = 'GET_LIST_STATISTIC_STACKING_REQUESTED';
export const GET_LIST_STATISTIC_STACKING_SUCCESS = 'GET_LIST_STATISTIC_STACKING_SUCCESS';
export const GET_LIST_STATISTIC_STACKING_FAILED = 'GET_LIST_STATISTIC_STACKING_FAILED';

export const GET_STAT_REQUESTED = 'GET_STAT_REQUESTED';
export const GET_STAT_SUCCESS = 'GET_STAT_SUCCESS';
export const GET_STAT_FAILED = 'GET_STAT_FAILED';
