export const GET_SYSTEM_CONFIG_REQUESTED = 'GET_SYSTEM_CONFIG_REQUESTED';
export const GET_SYSTEM_CONFIG_SUCCESS = 'GET_SYSTEM_CONFIG_SUCCESS';
export const GET_SYSTEM_CONFIG_FAILED = 'GET_SYSTEM_CONFIG_FAILED';

export const GET_CONFIG_COMMISSION_REQUESTED = 'GET_CONFIG_COMMISSION_REQUESTED';
export const GET_CONFIG_COMMISSION_SUCCESS = 'GET_CONFIG_COMMISSION_SUCCESS';
export const GET_CONFIG_COMMISSION_FAILED = 'GET_CONFIG_COMMISSION_FAILED';

export const GET_EXCHANGE_RATE_REQUESTED = 'GET_EXCHANGE_RATE_REQUESTED';
export const GET_EXCHANGE_RATE_SUCCESS = 'GET_EXCHANGE_RATE_SUCCESS';
export const GET_EXCHANGE_RATE_FAILED = 'GET_EXCHANGE_RATE_FAILED';
