export const GET_LIST_ACCOUNT_REQUESTED = 'GET_LIST_ACCOUNT_REQUESTED';
export const GET_LIST_ACCOUNT_SUCCESS = 'GET_LIST_ACCOUNT_SUCCESS';
export const GET_LIST_ACCOUNT_FAILED = 'GET_LIST_ACCOUNT_FAILED';

export const GET_STAT_REQUESTED = 'GET_STAT_REQUESTED';
export const GET_STAT_SUCCESS = 'GET_STAT_SUCCESS';
export const GET_STAT_FAILED = 'GET_STAT_FAILED';
