export const GET_LIST_PRIZE_SPIN_REQUESTED = 'GET_LIST_PRIZE_SPIN_REQUESTED';
export const GET_LIST_PRIZE_SPIN_SUCCESS = 'GET_LIST_PRIZE_SPIN_SUCCESS';
export const GET_LIST_PRIZE_SPIN_FAILED = 'GET_LIST_PRIZE_SPIN_FAILED';
