export const GET_LIST_TRANSACTION_P2P_REQUESTED = 'GET_LIST_TRANSACTION_P2P_REQUESTED';
export const GET_LIST_TRANSACTION_P2P_SUCCESS = 'GET_LIST_TRANSACTION_P2P_SUCCESS';
export const GET_LIST_TRANSACTION_P2P_FAILED = 'GET_LIST_TRANSACTION_P2P_FAILED';

export const GET_STAT_TRANSACTION_P2P_REQUESTED = 'GET_STAT_TRANSACTION_P2P_REQUESTED';
export const GET_STAT_TRANSACTION_P2P_SUCCESS = 'GET_STAT_TRANSACTION_P2P_SUCCESS';
export const GET_STAT_TRANSACTION_P2P_FAILED = 'GET_STAT_TRANSACTION_P2P_FAILED';
