// account
export const GET_LIST_ACCOUNT_REQUESTED = 'GET_LIST_ACCOUNT_REQUESTED';
export const GET_LIST_ACCOUNT_SUCCESS = 'GET_LIST_ACCOUNT_SUCCESS';
export const GET_LIST_ACCOUNT_FAILED = 'GET_LIST_ACCOUNT_FAILED';

//event reward
export const GET_EVENTS_REQUESTED = 'GET_EVENTS_REQUESTED';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED';

export const GET_BROKERS = 'GET_BROKERS';
export const GET_BROKER_SUCCESS = 'GET_BROKER_SUCCESS';
export const GET_BROKER_FAILED = 'GET_BROKER_FAILED';

export const GET_USERS_BY_KEYWORD = 'GET_USERS_BY_KEYWORD';
export const GET_USERS_BY_KEYWORD_SUCCESS = 'GET_USERS_BY_KEYWORD_SUCCESS';
export const GET_USERS_BY_KEYWORD_FAILED = 'GET_USERS_BY_KEYWORD_FAILED';

export const GET_USERS_REWARDED = 'GET_USERS_REWARDED';
export const GET_USERS_REWARDED_SUCCESS = 'GET_USERS_REWARDED_SUCCESS';
export const GET_USERS_REWARDED_FAILED = 'GET_USERS_REWARDED_FAILED';
