export const GET_LIST_FRIEND_INVITATION_DETAIL_REQUESTED = 'GET_LIST_FRIEND_INVITATION_DETAIL_REQUESTED';
export const GET_LIST_FRIEND_INVITATION_DETAIL_SUCCESS = 'GET_LIST_FRIEND_INVITATION_DETAIL_SUCCESS';
export const GET_LIST_FRIEND_INVITATION_DETAIL_FAILED = 'GET_LIST_FRIEND_INVITATION_DETAIL_FAILED';

export const GET_EVENT_BY_ID_REQUESTED = 'GET_EVENT_BY_ID_REQUESTED';
export const GET_EVENT_BY_ID_SUCCESS = 'GET_EVENT_BY_ID_SUCCESS';
export const GET_EVENT_BY_ID_FAILED = 'GET_EVENT_BY_ID_FAILED';
