export const GET_LIST_REFERRAL_REQUESTED = 'GET_LIST_REFERRAL_REQUESTED';
export const GET_LIST_REFERRAL_SUCCESS = 'GET_LIST_REFERRAL_SUCCESS';
export const GET_LIST_REFERRAL_FAILED = 'GET_LIST_REFERRAL_FAILED';
