export const GET_LIST_MOBILE_USER_REQUESTED = 'GET_LIST_MOBILE_USER_REQUESTED';
export const GET_LIST_MOBILE_USER_SUCCESS = 'GET_LIST_MOBILE_USER_SUCCESS';
export const GET_LIST_MOBILE_USER_FAILED = 'GET_LIST_MOBILE_USER_FAILED';
