export const GET_CATEGORY_MASTER_REQUESTED = 'GET_CATEGORY_MASTER_REQUESTED';
export const GET_CATEGORY_MASTER_SUCCESS = 'GET_CATEGORY_MASTER_SUCCESS';
export const GET_CATEGORY_MASTER_FAILED = 'GET_CATEGORY_MASTER_FAILED';

export const GET_LIST_CAMPAIGN_REQUESTED = 'GET_LIST_CAMPAIGN_REQUESTED';
export const GET_LIST_CAMPAIGN_SUCCESS = 'GET_LIST_CAMPAIGN_SUCCESS';
export const GET_LIST_CAMPAIGN_FAILED = 'GET_LIST_CAMPAIGN_FAILED';
